TodowooProject/urls.py
from django.contrib import admin
from django.urls import path
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),

    #AUTH

    path('signup/', views.signup ,name ='sign'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),

    #TODOS
    path('', views.home, name='home'),
    path('create/', views.create, name='createtodo'),
    path('todo/<int:todo_id>', views.showtodo, name='todoID'),
    path('complete/<int:todo_id>', views.complete, name='completeTodo'),
    path('completed/', views.completed, name='completed'),
    path('delete/<int:todo_id>', views.deleteToDo, name='deleteToDo'),

]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

class ToDo(models.Model):
    title = models.CharField(max_length=100)
    discription = models.TextField(blank=True)
    createdDate = models.DateTimeField(auto_now_add=True )
    finishedDate = models.DateTimeField(null=True,blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User , on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todo/forms.py
from django.forms import ModelForm
from .models import ToDo

class ToDoForm(ModelForm):
    class Meta:
        model = ToDo
        fields = ['title', 'discription', 'important']

todo/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render ,redirect ,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import login, logout , authenticate
from .forms import ToDoForm
from .models import ToDo
from django.utils import  timezone

def signup(request):
    if request.method == 'GET':
        return render(request ,'todo/signup.html')


    else:
        Password = request.POST["password"]
        Password2 = request.POST["password2"]
        UserName = request.POST["name"]

        if Password == Password2:
            if not User.objects.filter(username = UserName).exists() :
                Person = User.objects.create_user(username=UserName , password=Password)
                Person.save()
                login(request , Person)
                return redirect('home')
            else:
                return render(request, 'todo/signup.html', {'error': 'Пользователь с таким именем уже существует'})

        else :
            return render(request, 'todo/signup.html' ,{'error' : 'Пароли не совпадают'})

@login_required()
def create(request):
    if request.method == "GET":
        return  render(request,'todo/create.html', {'form': ToDoForm()})
    else:
        form = ToDoForm(request.POST)
        newtodo = form.save(commit=False)
        newtodo.user = request.user
        newtodo.save()
        return redirect('home')

@login_required
def home(request):
    todos = ToDo.objects.filter(user=request.user ,finishedDate__isnull=True).order_by('-createdDate')
    return render(request ,'todo/home.html', {'todos': todos})
@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

def loginuser(request):
    if request.method == "GET":
        return render(request, 'todo/login.html')
    else:
        Person = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if Person is None :
            return render(request, 'todo/login.html', {'error': 'Неверные данные для входа'})
        else:
            login(request,Person)
            return redirect('home')

@login_required
def showtodo(request ,todo_id):
    todo = get_object_or_404(ToDo ,pk=todo_id ,user = request.user)

    if request.method == "GET":
        todo_form = ToDoForm(instance=todo)
        return render(request, 'todo/todoview.html', {"form":todo_form , "todo":todo})
    else:
        form = ToDoForm(request.POST , instance=todo)
        form.save()
        return redirect('home')

@login_required
def complete(request ,todo_id):
    if request.method == "POST":
        todo = get_object_or_404(ToDo , pk =todo_id , user = request.user)
        todo.finishedDate = timezone.now()
        todo.save()
        return redirect('home')

@login_required
def completed(request):
    todos = ToDo.objects.filter(user = request.user , finishedDate__isnull=False).order_by('-finishedDate')
    return render(request ,'todo/completed.html' ,{'todos':todos})

@login_required
def deleteToDo(request ,todo_id):
    try:
        todos = get_object_or_404(ToDo ,pk = todo_id , user = request.user)
        todos.delete()
        return redirect('home')
    except:
        return redirect('home')

todo/templates/todo/base.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="{% static 'logo.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
      ToDo Sayf
    </a>
  </div>
  <div class="container-fluid col-xs-12 col-md-4" style="padding: 1px">
        <a style="margin-left:1%;margin-right:1% " class="nav-link active" href="/">Текущие задачи</a>
        <a style="margin-left:1%;margin-right:1% " class="nav-link active" aria-current="page" href="/completed">Выполненные</a>
        <a style="margin-left:1%;margin-right:1% " class="nav-link" href="{% url 'createtodo' %}">Создать</a>
      <button type="submit" class="btn btn-warning" form="logout">Logout {{ user.username }}</button>
  </div>
</nav>
 <form action="{% url 'logoutuser' %}" method="POST" id="logout">{% csrf_token %}
    </form>


{% block content %}{% endblock %}

todo/templates/todo/completed.html
{% extends 'todo/base.html' %}
{% block content %}
    <h3>Выполненные задачи</h3>
    {% for todo in todos %}
    <div class="list-group" style="margin-bottom: 1%;margin-top: 1%">


                <a  href="{% url 'todoID' todo.pk %} " class="list-group-item list-group-item-action">
                {% if todo.important %}<b>{% endif %}{{ todo.title }}{% if todo.important %}</b>{% endif %}
                {% if todo.discription %}-- {{ todo.discription }}{% endif %}
                </a>

        </div>

    {% endfor %}


{% endblock %}

todo/templates/todo/create.html
{% extends 'todo/base.html' %}
{% block content %}
    <h1>Создать новую задачу</h1>

<form action="{% url 'createtodo' %}" method="post" style="width: 50%">{% csrf_token %}
  <div class="mb-3">
    <label for="id_titl" class="form-label">Название</label>
    <input name="title" type="text" class="form-control" required id="id_titl" maxlength="100">
  </div>

  <div class="mb-3">
      <label for="id_titl" class="form-label">Описание</label>
      <textarea name="discription"  class="form-control" id="id_discription" cols="40" rows="10"></textarea>

  </div>

    <div class="mb-3 form-check">
        <label class="form-check-label" for="id_important">Важно</label>
        <input type="checkbox" class="form-check-input"  name="important" id="id_important">
  </div>

    <button type="submit" class="btn btn-primary">Создать заметку</button>
</form>
{% endblock %}

todo/templates/todo/home.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
{% extends 'todo/base.html' %}
{% block content %}
    <h3>Текущие задачи</h3><br>

    <div class="list-group" >

        {% for todo in todos %}
            <form action="{% url 'completeTodo' todo.pk %}" method="POST" >
                {% csrf_token %}

                <a href="{% url 'todoID' todo.pk %} " class="list-group-item list-group-item-action">
             {% if todo.important %}<b>{% endif %}{{ todo.title }}{% if todo.important %}</b>{% endif %}
                    {% if todo.discription %}-- {{ todo.discription }}{% endif %}


                    <button style="margin-left: 5%" type="submit" class="btn btn-success">Выполнено </button>
                </a>
            </form>


        {% endfor %}
</div>
{% endblock %}

todo/templates/todo/login.html
{% extends 'todo/loginbase.html' %}
{% block logincontent %}
{% load static %}


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/login.css'%}">

<div class="login">
    <div class="container text-center" >
    <h1>Login</h1>
    <h1>{{ error }}</h1>
<form action="{% url 'loginuser' %}" method="post">{% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" >Адрес электронной почты</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username">
    <div id="emailHelp" class="form-text">Мы никогда никому не передадим вашу электронную почту.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Пароль</label>
    <input type="password" class="form-control" id="exampleInputPassword1 " name="password">
  </div>
    <button type="submit" class="btn btn-primary">Отправить</button>
</form>
<br><a href="/signup">Sign up</a>
</div>
</div>
{% endblock %}

todo/templates/todo/loginbase.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
{% load static %}

<nav class="navbar bg-body-tertiary text-bg-primary p-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="{% static 'logo.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
      ToDo Sayf
    </a>
  </div>
</nav>

{% block logincontent %}
{% endblock %}

todo/templates/todo/signup.html
{% extends 'todo/loginbase.html' %}
{% block logincontent %}
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/login.css'%}">

<div class="login">
    <div class="container text-center" >
    <h1>Sign Up</h1>
    <h1>{{ error }}</h1>
<form action="{% url 'sign' %}" method="post">{% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" >Username</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">
    <div id="emailHelp" class="form-text">Мы никогда никому не передадим вашу электронную почту.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Пароль</label>
    <input type="password" class="form-control" id="exampleInputPassword1 " name="password">
  </div>
      <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Повторите пароль</label>
    <input type="password" class="form-control" id="exampleInputPassword1 " name="password2">
  </div>
    <button type="submit" class="btn btn-primary">Отправить</button>
</form>
<br><a href="/login">Login</a>
</div>
</div>
{% endblock %}

todo/templates/todo/todoview.html
{% extends 'todo/base.html' %}
{% block content %}

{% if todo.finishedDate is null %}

<h2>{{ todo.title }}</h2>


<div style="width: 50%">
<form action="{% url 'todoID' todo.pk %}" method="post" style="width: 100%" id="date">{% csrf_token %}
  <div class="form-group">
    <label for="id_titl" class="form-label">Название</label>
    <input name="title" type="text" class="form-control" required id="id_titl" maxlength="100" value="{{ todo.title }}">
  </div>

  <div class="form-group">
      <label for="id_titl" class="form-label">Описание</label>
      <textarea  name="discription"  class="form-control"  id="id_discription" cols="40" rows="10">{{ todo.discription }}</textarea>

  </div>

    <div class="form-group" style="margin-top: 1%">
        <label class="form-check-label" for="id_important">Важно</label>
        <input {% if todo.important %}checked{% endif %} type="checkbox" class="form-check-input"  name="important" id="id_important">
  </div>

</form>

<div class="row">
  <div class="col">
   <button form="date" type="submit" class="btn btn-primary form-control">Сохранить</button>
  </div>
  <div class="col">
     <button type="submit" class="btn btn-primary form-control" form="complete" style="background-color: green;border-color: green">Выполнено</button>
  </div>
  <div class="col">
    <button form="delete" type="submit" class="btn btn-primary form-control" style="background-color: brown;border-color: brown">Удалить</button>
  </div>
</div>


</div>



<form action="{% url 'deleteToDo' todo.pk %}" id="delete">
    {% csrf_token %}
</form>

<form action="{% url 'completeTodo' todo.pk %}" method="POST" id="complete">
    {% csrf_token %}
</form>



    {% else %}

    <h3>{{ todo.title }}</h3>
   {% if todo.discription %}
   	 <h3>{{ todo.discription }}</h3>
   {% endif %}
    <h5> Начато {{ todo.createdDate }} --- Закончено {{ todo.finishedDate }}</h5>



  {% endif %}
{% endblock %}